### ISSUE TITLE
A registry addon

### ISSUE THREAD

**Issue by hutchic** [Kong/kubernetes-testing-framework#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As someone developing Kong
I want the ability to run a bespoke locally built docker image
So that I can test my code locally and within CI

### Proposed Solution

Prior art of running a local docker registry and connecting it into kind exists [here](https://github.com/Kong/khcp/blob/master/charts/local.sh#L1-L44)

Generally speaking taking a flag `--gateway-image=myimage` that gets from my local docker images and is the image KTF uses to run the gateway

**Comment by shaneutt** [comment]
This has additional benefit for CI because it could allow for seeding images from a cache in Github actions, we should see if we can _also_ build this for a use case where the caller would have simple calls to seed the registry with multiple images.
