### ISSUE TITLE
Kong CRDs not disabled by proxy-only mode

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-testing-framework#19]
Our proxy-only deployment mode still deploys CRDs, which given the naming seems incorrect.

We need to disable them, and then clean up any related workarounds in [KIC](https://github.com/kong/kubernetes-ingress-controller).

**Comment by rainest** [comment]
Does this indeed need a toggle? Simply turning it off is pretty easy:

```
diff --git a/pkg/helm/kong.go b/pkg/helm/kong.go
index 21370e0..12813cf 100644
--- a/pkg/helm/kong.go
+++ b/pkg/helm/kong.go
@@ -46,6 +46,7 @@ func DeployKongProxyOnly(clusterName string) error {
 
        install := exec.Command("helm", "install", "ingress-controller", "kong/kong",
                "--kubeconfig", tmpFile.Name(),
+               "--skip-crds",
                "--create-namespace", "--namespace", "kong-system",
                // this function assumes you're bringing your own controller
                "--set", "ingressController.enabled=false",
```
`DeployKongProxyOnly()` doesn't currently expose any configuration at the moment, but given what it claims to do it doesn't seem like CRD installation needs a toggle, since those are always the domain of the controller.

**Comment by shaneutt** [comment]
Your suggestion sounds good to me :+1:
