### ISSUE TITLE
Teardown capability

### ISSUE THREAD

**Issue by hutchic** [Kong/kubernetes-testing-framework#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Folks that aren't fluent in k8s / kind will litter their environment with ktf environments

### Proposed Solution

Some sort of clean / teardown command. List the KTF created environments and allow users to select the environment to tear down default to all

**Comment by shaneutt** [comment]
@hutchic we do already have the `ktf envs delete --name <name>` command. Is there some enhancement that you would like to see with that existing functionality?

**Comment by hutchic** [comment]
If I recall the use case we got stuck on I'll reopen but will close for now
