### ISSUE TITLE
Environment Diagnostics

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-testing-framework#306]
### Problem Statement

When tests using KTF fail (particularly E2E tests in [KIC](https://github.com/kong/kubernetes-ingress-controller)) on conditions that aren't met currently the way to investigate this is to reproduce the problem locally and investigate the cluster there. This however is problematic when we get a transient failure or flake. The purpose of this issue is to enable the creation of diagnostic dumps for KTF clusters so that users like KIC can take and collect a dump before the cluster is cleaned up as a part of the CI run.

### Additional information

Potentially taking a backup of the entire API with something like [velero](https://velero.io) might be viable. I do remember in the past seeing tools that will let you host a dump of the API server and interrogate it with `kubectl`, though I've forgotten the name of that tool and can't find it. Suffice to say when we implement this we should be certain to check the open source ecosystem for existing tools.

### Acceptance Criteria

- [x] when a KTF environment fails to create a diagnostic bundle is automatically generated
- [x] as a user of the go library I can trigger a diagnostic dump for the cluster which returns the file(s) to me to collect as an artifact in CI
- [x] diagnostic dumps should contain as much API state as possible
- [x] diagnostic dumps should contain pod logs

**Comment by mflendrich** [comment]
We should figure out how to prioritize issue pairs (where one describes the use case and the other describes the technical backing), which is the case for this issue & Kong/kubernetes-ingress-controller#2625.

Prioritizing the latter for now, with the intention that this one will be done along the way.

**Comment by rainest** [comment]
The cleanup utility would be a good point to collect state (all Kubernetes resources, Kong config) if we can find a way to inform it of a test's failure. This may be difficult to do in a non-kludgy way since it's called in a defer and the test result is part of testify state (not sure if there's a way to get it out).

**Comment by pmalek** [comment]
> This may be difficult to do in a non-kludgy way since it's called in a defer and the test result is part of testify state (not sure if there's a way to get it out).

Why couldn't we just use [`t.Failed()`](https://pkg.go.dev/testing#T.Failed) and pass that down ?

**Comment by randmonkey** [comment]
All the ACs are met in current KTF, close this.

**Comment by jrsmroz** [comment]
What are the PRs that closes this issue? They're not linked.
