### ISSUE TITLE
Releases not triggering on tag creation

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-testing-framework#337]
The last several successful runs of release-testing did create tags, but this did not trigger a release, and we've had to [dispatch a release job manually](https://github.com/Kong/kubernetes-testing-framework/actions/workflows/release.yaml). It is not obvious why this happens, as I don't see anything in the [the last few tags](https://github.com/Kong/kubernetes-testing-framework/tags) that would prevent them from matching the condition: https://github.com/Kong/kubernetes-testing-framework/blob/633ccee769f9ff237756961c69ae9c89b92432b7/.github/workflows/release.yaml#L3-L7

The release workflow has not changed since before this started happening. The release testing workflow has, to add the new license retrieval script, but I do not see how this would affect the trigger since the output (the last step that creates the tag) has not changed since before this began.

Mitigation is pretty simple since we can just run the second step manually, but ideally we shouldn't have to.

**Comment by pmalek** [comment]
Still happening https://github.com/Kong/kubernetes-testing-framework/actions/runs/3174341904/jobs/5171012212#step:9:9

**Comment by jrsmroz** [comment]
I did some reaserch and found [this](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow):

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. For more information, see "[Authenticating with the GITHUB_TOKEN](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)."
> 
> If you do want to trigger a workflow from within a workflow run, you can use a personal access token instead of GITHUB_TOKEN to trigger events that require a token. You'll need to create a personal access token and store it as a secret. To minimize your GitHub Actions usage costs, ensure that you don't create recursive or unintended workflow runs. For more information about creating a personal access token, see "[Creating a personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)." For more information about storing a personal access token as a secret, see "[Creating and storing encrypted secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)."
