### ISSUE TITLE
Support updated GKE auth system

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-testing-framework#345]
Per https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke the 1.25 release will begin requiring a kubectl plugin to use kubectl with GKE. This likely requires changes to client-go usage (to use the same [plugin system](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) used by the kubectl plugin) when not using in-cluster configuration.

We need to:
- Determine how to use the plugin in KTF's kubectl invocations, or if not possible try to warn about its absence.
- Determine if we need to make changes to client-go usage.
- Develop recommendations for downstream, which will probably need to make similar changes.

**Comment by mflendrich** [comment]
won't fix - seems that our testenv does not require this to be successful and it's unclear what the benefit of this change would be.

**Comment by mflendrich** [comment]
further work
- [ ] Make the test harness log the parameters of the created GKE cluster
