### ISSUE TITLE
Support k8s v1.25

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-testing-framework#364]
This issue tracks support for kubernetes v1.25.

So far these are the features/components that make ktf not fully support k8s v1.25:

- `metallb` addon using version `v0.12.1` which uses `PodSecurityPolicy` which [was removed after being deprecated v1.21](https://kubernetes.io/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/#podsecuritypolicy-removal)

  ```
  Error: tests failed: failed to deploy addon metallb: resource mapping not found for name: "controller" namespace: "" from "https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
  ensure CRDs are installed first
  resource mapping not found for name: "speaker" namespace: "" from "https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
  ```

**Comment by pmalek** [comment]
This is already biting us: https://github.com/Kong/kubernetes-ingress-controller/runs/8210249325?check_suite_focus=true#step:6:129

**Comment by shaneutt** [comment]
It doesn't appear we have time for `v1.25.x` support in KIC `v2.6.0` which we expect to release in the next couple weeks: I would recommend that we make adjustments in CI to cap out the cluster test versions at `v1.24.x` for now, and consider this issue required for the follow up KIC `v2.7.0` release.

**Comment by shaneutt** [comment]
Yes, this suggests we are getting `kind` [v0.15.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.15.0) which was released in the last week and will deploy Kubernetes `v1.25.0` by default.

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-testing-framework/pull/369 pins this for KTF. It includes TODO comments that mention this issue URL that we'll want to remove once we have a permanent fix ready.

**Comment by randmonkey** [comment]
Metallb addon might become a blocker of this. It has not proposed a release that removes `PodSecurityPolicy` yet. issue: https://github.com/metallb/metallb/issues/1401

**Comment by shaneutt** [comment]
> Metallb addon might become a blocker of this. It has not proposed a release that removes `PodSecurityPolicy` yet. issue: [metallb/metallb#1401](https://github.com/metallb/metallb/issues/1401)

It appears [v0.13.5](https://github.com/metallb/metallb/releases/tag/v0.13.5) fixed this, as per the release notes:

https://metallb.universe.tf/release-notes/#version-0-13-5

So unless I'm missing something, we should be OK?

**Comment by pmalek** [comment]
Given that other changes didn't break anything else worth a shot to swap https://github.com/Kong/kubernetes-testing-framework/blob/3fcbadf6ceb35b922087d338b2d5e59dce3a115d/pkg/clusters/addons/metallb/metallb.go#L122 with `https://raw.githubusercontent.com/metallb/metallb/v0.13.5/config/manifests/metallb-native.yaml`
