### ISSUE TITLE
setup-kong-license silently fails

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-testing-framework#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

setup-kong-license silently fails. Possibly being a reason for failure of `TestKongEnterprisePostgres` test.

From the pipeline run https://github.com/Kong/kubernetes-testing-framework/actions/runs/3299432277/jobs/5454573296

```bash
echo "encrypted=$(gpg --symmetric --batch --passphrase  --output - <(echo ${KONG_LICENSE_DATA}) | base64 -w0)" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    KONG_LICENSE_DATA: {"license":{"payload":{"admin_seats":"5","customer":"automation","dataplanes":"100","license_creation_date":"[2](https://github.com/Kong/kubernetes-testing-framework/actions/runs/3299432277/jobs/5454573296#step:3:2)022-10-10","license_expiration_date":"2022-11-20","license_key":"***","product_subscription":"Konnect Enterprise","support_plan":"None"},"signature":"***","version":"1"}}
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: error creating passphrase: Invalid passphrase
gpg: symmetric encryption of '/dev/fd/6[3](https://github.com/Kong/kubernetes-testing-framework/actions/runs/3299432277/jobs/5454573296#step:3:3)' failed: Invalid passphrase
````

### Expected Behavior

Should work

### Steps To Reproduce

```markdown
Detected during pipeline run
```

**Comment by jrsmroz** [comment]
@pmalek Can you double check `LICENSE_ENCRYPTION_PASSWORD` secret?

**Comment by jrsmroz** [comment]
It remains mystery for me why it sometimes fails. Yet, sometimes it works. My guess is the license may contain a special character that breaks the GitHub  processing. When the license is not enclosed in double quotes it works.

**Comment by pmalek** [comment]
Oh, this might be because we didn't add the `LICENSE_ENCRYPTION_PASSWORD` to dependabot's secrets 🤦 

I've added that now (this can be an arbitrary string since it's just used to encrypt and decrypt the password in the same action.

```
echo <VALUE> | gh secret set LICENSE_ENCRYPTION_PASSWORD --app dependabot
```

**Comment by jrsmroz** [comment]
Sure, we can check that out.

**Comment by jrsmroz** [comment]
Seems fixed. Closing by secret change.
