### ISSUE TITLE
Release uses an unsupported action

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-testing-framework#458]
Release workflow [uses](https://github.com/Kong/kubernetes-testing-framework/blob/02e4133d3dd89eaab7741e258c5cefa6d882f1cf/.github/workflows/release.yaml#L47) an unsupported release action: [`actions/create-release@v1`](https://github.com/actions/create-release).

Because it uses the [deprecated `set-output`](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) command, we'll have to approach this sooner or later.

Exemplar CI failure: https://github.com/Kong/kubernetes-testing-framework/actions/runs/3628481705/jobs/6119549896#step:5:12

## Proposed solution

Use an action that will not yield warnings and not be marked as unsupported, e.g. [`softprops/action-gh-release`](https://github.com/softprops/action-gh-release)

## Acceptance criteria

- release pipeline uses an action that is not marked as unsupported

**Comment by mflendrich** [comment]
@pmalek please add a proposed solution and AC
