### ISSUE TITLE
Addons installed by helm are prone to external services errors during installation

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-testing-framework#476]
## Problem statement

Whenever addons that utilize `helm` for installation ([`kong`](https://github.com/Kong/kubernetes-testing-framework/blob/d0f8f0b1c588224b64cfee772fff3e73fb365db9/pkg/clusters/addons/kong/addon.go#L253) and [`kuma`](https://github.com/Kong/kubernetes-testing-framework/blob/02e4133d3dd89eaab7741e258c5cefa6d882f1cf/pkg/clusters/addons/kuma/addon.go#L144)) they are prone to failure due to hosting services that host the helm charts.

Exemplar failure: 

```
=== FAIL: test/integration  (0.00s)
INFO: setting up test environment
INFO: configuring cluster for testing environment
INFO: no existing cluster found, deploying using Kubernetes In Docker (KIND)
INFO: build a new KIND cluster with version 1.25.3
INFO: building test environment
WARNING: failure occurred, performing test cleanup
Error: tests failed: failed to deploy addon kong: Error: INSTALLATION FAILED: failed to fetch https://github.com/Kong/charts/releases/download/kong-2.13.1/kong-2.13.1.tgz : 503 Service Unavailable
```

https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3691517677/jobs/6249752001#step:6:48

This causes the tests to fail.

## Proposed solution

Introduce a (configurable?) retry mechanism which will retry whenever an error like this is received during helm chart installation.

## Acceptance criteria

- as a user I can use helm based addons without worrying about intermittent network failures

**Comment by mflendrich** [comment]
@pmalek please fill in the AC, thx
