### ISSUE TITLE
Update kustomize api dependency to v0.13

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-testing-framework#601]
The purpose of this task is to get our `sigs.k8s.io/kustomize/api` dependency updated to `v0.13+`.

**Comment by pmalek** [comment]
Already at v0.16.0 https://github.com/Kong/kubernetes-testing-framework/blob/a13ab7491ee275224c17d7b3b374fbc8624a7a7f/go.mod#L37
