### ISSUE TITLE
GKE Existing Cluster Loader

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-testing-framework#66]
Currently Environments can have a cluster of one of several types, but only a single cluster and the GKE cluster implementation (in particular) doesn't have an option to use an existing cluster. The purpose of this task is to add functionality which would support loading a testing `Environment` with an existing GKE cluster.

Acceptance Criteria:
- [x] a `clusters.Cluster` can be created from an existing GKE cluster
- [x] GKE based `Clusters` can be loaded and used in `Environments`

**Comment by ccfishk** [comment]
wonder if we can decouple GKE cluster deployment from KIC. 
Does KTF deploy GKE using command line ?

**Comment by shaneutt** [comment]
> wonder if we can decouple GKE cluster deployment from KIC.
> Does KTF deploy GKE using command line ?

No, it using the golang API.

**Comment by shaneutt** [comment]
Resolved by https://github.com/Kong/kubernetes-testing-framework/pull/67
